"""Trainable, serializable high-level interface for the GCTR policy.

The lower-level :func:`specops_gctr.gctr_policy` function accepts an already
predicted Gaussian.  This module connects the complete learned algorithm:
supervised angle targets -> graph-conditioned Gaussian -> held-out error
calibration -> uncertainty-priced search.  Calibration graphs are required to
be disjoint from the angle-training graphs so the convenience API does not
silently introduce the leakage excluded by the manuscript protocol.
"""
from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path
from typing import Iterable, Optional, Sequence

import networkx as nx
import numpy as np
import torch

from .baselines import gctr_policy
from .graphs import Instance, graph_feature_dim, laplacian_spectral_features
from .model import ErrorCalibrator, GraphConditionedGaussian, build_dense_batch
from .pipeline import Config, budget_rule, concentration_angles, train_model
from .qaoa import qaoa_expectation


@dataclass(frozen=True)
class GCTRPrediction:
    """Graph-conditioned search policy predicted for one instance."""

    mean: np.ndarray
    variance: np.ndarray
    uncertainty: float
    allocation: dict


def _as_instances(values: Iterable[Instance], name: str) -> list[Instance]:
    out = list(values)
    if not out or not all(isinstance(item, Instance) for item in out):
        raise ValueError(f"{name} must contain at least one Instance")
    return out


def _prediction_graph(graph: nx.Graph) -> nx.Graph:
    """Validate and normalize a graph without constructing a statevector.

    This path is intentionally independent of :meth:`Instance.from_networkx`,
    whose exact MaxCut value and cost diagonal are exponential in the vertex
    count. Prediction itself needs only graph features.
    """
    if (not isinstance(graph, nx.Graph) or graph.is_directed()
            or graph.is_multigraph()):
        raise TypeError("graph must be a simple undirected networkx.Graph")
    if graph.number_of_nodes() < 2:
        raise ValueError("graph must contain at least two nodes")
    if graph.number_of_edges() == 0:
        raise ValueError("graph must contain at least one edge")
    if nx.number_of_selfloops(graph):
        raise ValueError("self-loops are not supported")
    for _, _, attributes in graph.edges(data=True):
        if "weight" in attributes and float(attributes["weight"]) != 1.0:
            raise ValueError("only unweighted/unit-weight graphs are supported")
    return nx.convert_node_labels_to_integers(
        graph.copy(), ordering="default")


class GCTRPolicyModel:
    """Fitted graph-conditioned Gaussian and held-out budget calibrator.

    Use :meth:`fit` when angle targets have already been generated by a trusted
    offline optimizer.  The fitted object predicts all operational policy
    components for a new graph and can run the counted search directly.
    """

    format_version = 1

    def __init__(self, config: Config, model: GraphConditionedGaussian,
                 concentration: Sequence[float]):
        self.config = config
        self.model = model.cpu().eval()
        self.concentration = np.asarray(concentration, dtype=float)
        if self.concentration.shape != (2 * config.p_depth,):
            raise ValueError("concentration must have shape (2 * p_depth,)")
        required = ("error_calibrator", "_emb_mean", "_emb_std",
                    "_u_med", "_u_iqr")
        if any(not hasattr(self.model, name) for name in required):
            raise ValueError("model is missing held-out calibration state")

    @classmethod
    def fit(cls, train_instances: Iterable[Instance], target_angles,
            calibration_instances: Iterable[Instance], *,
            config: Optional[Config] = None, target_errors=None,
            verbose: bool = False) -> "GCTRPolicyModel":
        """Fit the complete policy from labelled training graphs.

        ``target_angles`` contains one offline target vector per training graph.
        If ``target_errors`` is omitted, it is computed as one minus the exact
        expectation ratio attained by each target vector.  Calibration graphs
        need no angle labels: the frozen mean head is evaluated on them and the
        error calibrator learns only from those held-out residuals.
        """
        cfg = replace(config) if config is not None else Config()
        train = _as_instances(train_instances, "train_instances")
        calibration = _as_instances(
            calibration_instances, "calibration_instances")
        if len(calibration) < 2:
            raise ValueError(
                "calibration_instances must contain at least two instances")
        overlap = any(
            left.n == right.n
            and left.graph.number_of_edges() == right.graph.number_of_edges()
            and nx.is_isomorphic(left.graph, right.graph)
            for left in train for right in calibration
        )
        if overlap:
            raise ValueError(
                "training and calibration instances must be disjoint")

        angles = np.asarray(target_angles, dtype=float)
        expected_shape = (len(train), 2 * cfg.p_depth)
        if angles.shape != expected_shape or not np.all(np.isfinite(angles)):
            raise ValueError(
                f"target_angles must be finite with shape {expected_shape}")

        if target_errors is None:
            errors = []
            for instance, angle in zip(train, angles):
                ratio = qaoa_expectation(
                    instance.C, angle, instance.n) / instance.maxcut
                errors.append(max(0.0, 1.0 - ratio))
            errors = np.asarray(errors, dtype=float)
        else:
            errors = np.asarray(target_errors, dtype=float)
            if errors.shape != (len(train),) or not np.all(np.isfinite(errors)):
                raise ValueError(
                    f"target_errors must be finite with shape {(len(train),)}")
            if np.any(errors < 0):
                raise ValueError("target_errors must be nonnegative")

        data = {
            "train": train,
            "val": calibration,
            "tr_ang": angles,
            "tr_err": errors,
        }
        model, _, _ = train_model(cfg, data, verbose=verbose)
        return cls(cfg, model, concentration_angles(angles))

    def _features(self, graph: nx.Graph):
        features = laplacian_spectral_features(
            graph, self.config.spectral_k)
        adjacency = nx.to_numpy_array(graph, dtype=np.float32)
        return build_dense_batch([features], [adjacency])

    def predict_graph(self, graph: nx.Graph, *,
                      budget: Optional[int] = None) -> GCTRPrediction:
        """Predict a policy from graph structure without exact simulation.

        Unlike :meth:`predict` on an :class:`Instance`, this method does not
        compute an exact MaxCut value or allocate a ``2**n`` cost diagonal. It
        is the intended prediction path before calling
        :func:`specops_gctr.gctr_callback_policy` with a user backend.
        Dense spectral decomposition and adjacency construction still require
        roughly cubic time and quadratic memory in the number of vertices.
        """
        normalized = _prediction_graph(graph)
        cfg = replace(self.config)
        if budget is not None:
            if int(budget) != budget or budget < 1:
                raise ValueError("budget must be a positive integer")
            cfg.budget = int(budget)
            cfg.budget_cap_min = min(cfg.budget_cap_min, cfg.budget)

        X, A, M = self._features(normalized)
        self.model.eval()
        with torch.no_grad():
            pooled = self.model.embed(X, A, M)
            mean = self.model.mu_head(pooled)[0].cpu().numpy()
            logvar = self.model.logvar_head(pooled).clamp(-8.0, 2.0)[0]
            variance = torch.exp(logvar).cpu().numpy()
            normalized_embedding = (
                pooled - self.model._emb_mean) / self.model._emb_std
            uncertainty = float(torch.exp(
                self.model.error_calibrator(normalized_embedding)[0]).cpu())
        allocation = budget_rule(
            cfg, uncertainty, self.model._u_med, self.model._u_iqr)
        return GCTRPrediction(
            mean=np.asarray(mean, dtype=float),
            variance=np.asarray(variance, dtype=float),
            uncertainty=uncertainty,
            allocation=allocation,
        )

    def predict(self, instance: Instance, *,
                budget: Optional[int] = None) -> GCTRPrediction:
        """Predict from an exact-simulation :class:`Instance`."""
        if not isinstance(instance, Instance):
            raise TypeError("instance must be an Instance")
        return self.predict_graph(instance.graph, budget=budget)

    def optimize(self, instance: Instance, *, budget: Optional[int] = None,
                 target: Optional[float] = None,
                 target_fraction: Optional[float] = None,
                 radius_scale: Optional[float] = None,
                 n_gaussian_seeds: Optional[int] = None,
                 use_heuristic_seed: bool = True,
                 use_trust_region: bool = True,
                 shots: Optional[int] = None, seed: int = 0):
        """Predict and execute the counted GCTR search on one graph."""
        effective_budget = self.config.budget if budget is None else budget
        prediction = self.predict(instance, budget=effective_budget)
        if target is not None and target_fraction is not None:
            raise ValueError("supply target or target_fraction, not both")
        if target_fraction is not None:
            if not 0.0 < target_fraction <= 1.0:
                raise ValueError("target_fraction must lie in (0, 1]")
            target = float(target_fraction) * instance.maxcut
        seeds = (prediction.allocation["n_gaussian_seeds"]
                 if n_gaussian_seeds is None else n_gaussian_seeds)
        return gctr_policy(
            instance,
            budget=int(effective_budget),
            mu=prediction.mean,
            sigma_diag=prediction.variance,
            radius_scale=(self.config.radius_scale if radius_scale is None
                          else radius_scale),
            rng=np.random.default_rng(seed),
            sample_seed=seed,
            target=target,
            heuristic_angles=self.concentration,
            use_heuristic_seed=use_heuristic_seed,
            n_gaussian_seeds=seeds,
            budget_cap=prediction.allocation["T"],
            use_trust_region=use_trust_region,
            shots=shots,
        )

    def save(self, path) -> Path:
        """Save fitted weights and calibration state to ``path``."""
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        torch.save({
            "format_version": self.format_version,
            "config": self.config.to_dict(),
            "state_dict": self.model.state_dict(),
            "concentration": torch.as_tensor(
                self.concentration, dtype=torch.float64),
            "embedding_mean": self.model._emb_mean,
            "embedding_std": self.model._emb_std,
            "uncertainty_median": float(self.model._u_med),
            "uncertainty_iqr": float(self.model._u_iqr),
        }, destination)
        return destination

    @classmethod
    def load(cls, path) -> "GCTRPolicyModel":
        """Load a trusted checkpoint produced by :meth:`save` on CPU."""
        kwargs = {"map_location": "cpu"}
        # ``weights_only`` is not accepted by older supported torch releases.
        # Check the signature instead of catching arbitrary deserialization
        # errors, and retain compatibility with checkpoints produced here.
        import inspect
        if "weights_only" in inspect.signature(torch.load).parameters:
            kwargs["weights_only"] = True
        payload = torch.load(Path(path), **kwargs)
        if payload.get("format_version") != cls.format_version:
            raise ValueError("unsupported GCTR checkpoint format")
        raw = dict(payload["config"])
        for name in ("cross_sizes", "stability_seeds", "shot_levels"):
            if name in raw:
                raw[name] = tuple(raw[name])
        cfg = Config(**raw)
        model = GraphConditionedGaussian(
            graph_feature_dim(cfg.spectral_k), cfg.hidden_dim,
            cfg.num_layers, cfg.p_depth, use_spectral=cfg.use_spectral)
        model.error_calibrator = ErrorCalibrator(2 * cfg.hidden_dim)
        model.load_state_dict(payload["state_dict"])
        model._emb_mean = payload["embedding_mean"]
        model._emb_std = payload["embedding_std"]
        model._u_med = float(payload["uncertainty_median"])
        model._u_iqr = float(payload["uncertainty_iqr"])
        return cls(cfg, model, payload["concentration"].cpu().numpy())
