"""LaTeX table builders derived only from the committed source-data CSVs."""
from __future__ import annotations

from pathlib import Path
from typing import List

import pandas as pd

_EFF_DISPLAY = {
    "Random": "Random restarts",
    "Heuristic": "Concentration heuristic",
    "k-NN": "k-NN",
    "TQA": "TQA",
    "GNN point": "GNN point",
    "GCTR": "GCTR (ours)",
}

_HDR = ("% Auto-generated by specops-gctr from the committed source_data CSVs.\n"
        "% Do not edit by hand; run `gctr-reproduce` to regenerate.\n")


def _fmt_p(p) -> str:
    if pd.isna(p) or p == "":
        return "--"
    p = float(p)
    if p < 1e-4:
        return r"$<10^{-4}$"
    return f"${p:.3f}$"


def efficiency_table(src: Path) -> str:
    """Table `tab:efficiency` -- built entirely from Figure2_QueryEfficiency.csv.

    The p-value column is the two-sided paired Wilcoxon signed-rank test of
    GCTR against each baseline on per-instance evaluation counts.
    """
    df = pd.read_csv(src / "Figure2_QueryEfficiency.csv").set_index("method")
    lines = [
        _HDR + r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Method & Evaluations to target & $F_G(\theta)/C_{\max}$ & "
        r"Runtime (ms) & $p$ (vs.\ GCTR) \\",
        r"\midrule",
    ]
    for key, disp in _EFF_DISPLAY.items():
        if key not in df.index:
            continue
        r = df.loc[key]
        evals = f"${r['evaluations']:.0f}\\pm{r['evaluations_sd']:.0f}$"
        exp = f"${r['expectation_ratio']:.3f}\\pm{r['expectation_ratio_sd']:.3f}$"
        rt = f"${r['runtime_ms']:.0f}\\pm{r['runtime_ms_sd']:.0f}$"
        pv = _fmt_p(r.get("wilcoxon_p_vs_gctr", ""))
        lines.append(f"{disp} & {evals} & {exp} & {rt} & {pv} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def ablation_table(src: Path) -> str:
    """Table `tab:ablation` -- built entirely from Figure5_Ablation.csv (plus
    the point-prediction reference row from Figure2_QueryEfficiency.csv)."""
    df = pd.read_csv(src / "Figure5_Ablation.csv")
    f2 = pd.read_csv(src / "Figure2_QueryEfficiency.csv").set_index("method")
    lines = [
        _HDR + r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Variant & Evaluations to target & ECE & Spearman $\rho$ \\",
        r"\midrule",
    ]
    for _, r in df.iterrows():
        evals = f"${r['evaluations']:.0f}\\pm{r['evaluations_sd']:.0f}$"
        lines.append(f"{r['variant']} & {evals} & {r['ece']:.3f} & "
                     f"{r['spearman']:.3f} \\\\")
    if "GNN point" in f2.index:
        g = f2.loc["GNN point"]
        lines.append(f"Point prediction only & ${g['evaluations']:.0f}"
                     f"\\pm{g['evaluations_sd']:.0f}$ & -- & -- \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def write_tables(source_data_dir, tables_dir) -> List[str]:
    src = Path(source_data_dir)
    out = Path(tables_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths = []
    for name, fn in [("table_efficiency.tex", efficiency_table),
                     ("table_ablation.tex", ablation_table)]:
        p = out / name
        p.write_text(fn(src))
        paths.append(str(p))
    return paths
